parameters:
  matrixType: null
  name: null
  pool: {}
  customBuildLegGroupArgs: ""
  isTestStage: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - template: ../steps/init-docker-linux.yml
  - ${{ if eq(parameters.isTestStage, true) }}:

  - ${{ if eq(parameters.isTestStage, false) }}:
    - script: echo "##vso[task.setvariable variable=additionalGenerateBuildMatrixOptions]"
      displayName: Set GenerateBuildMatrix Variables
  - script: >
      $(runImageBuilderCmd) generateBuildMatrix
      --manifest $(manifest)
      --type ${{ parameters.matrixType }}
      --os-type '*'
      --architecture '*'
      --product-version-components $(productVersionComponents)
      ${{ parameters.customBuildLegGroupArgs }}
      $(imageBuilder.pathArgs)
      $(manifestVariables)
      $(additionalGenerateBuildMatrixOptions)
    displayName: Generate ${{ parameters.matrixType }} Matrix
    name: matrix
  - template: ../steps/cleanup-docker-linux.yml
