parameters:
  name: null
  pool: {}
  matrix: {}
  testJobTimeout: 60
  preBuildValidation: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: ${{ parameters.testJobTimeout }}
  steps:
  - template: ../steps/test-images-linux-client.yml
    parameters:
      preBuildValidation: ${{ parameters.preBuildValidation }}
