parameters:
  linuxAmdTestJobTimeout: 60

  noCache: false

  internalProjectName: null

  linuxAmd64Pool:
    vmImage: ubuntu-latest
stages:

################################################################################
# Build Images
################################################################################
- stage: Build
  condition: succeeded()
  jobs:
  - template: ../jobs/test-images-linux-client.yml
    parameters:
      name: PreBuildValidation
      pool: ${{ parameters.linuxAmd64Pool }}
      testJobTimeout: ${{ parameters.linuxAmdTestJobTimeout }}
      preBuildValidation: true
