parameters:
  publicProjectName: null

  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)

stages:

################################################################################
# Build Images
################################################################################
- stage: Build
  condition: succeeded()
  jobs:
  - template: ../jobs/test-images-linux-client.yml
    parameters:
      name: PreBuildValidation
      pool: ${{ parameters.linuxAmd64Pool }}
  - template: ../jobs/copy-base-images.yml
    parameters:
      name: CopyBaseImages
      pool: ${{ parameters.linuxAmd64Pool }}
      additionalOptions: "--manifest '$(manifest)' $(manifestVariables)"
      publicProjectName: ${{ parameters.publicProjectName }}
