parameters:
  buildMatrixType: platformDependencyGraph
  buildMatrixCustomBuildLegGroupArgs: ""
  linuxAmdBuildJobTimeout: 60

  linuxAmdTestJobTimeout: 60

  internalProjectName: null
  publicProjectName: null

  internalVersionsRepoRef: null
  publicVersionsRepoRef: null

  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)

stages:

################################################################################
# Build Images
################################################################################
- stage: Build
  condition: and(succeeded(), contains(variables['stages'], 'build'))
  jobs:
  #- template: ../jobs/test-images-linux-client.yml
  #  parameters:
  #    name: PreBuildValidation
  #    pool: ${{ parameters.linuxAmd64Pool }}
  #    testJobTimeout: ${{ parameters.linuxAmdTestJobTimeout }}
  #    preBuildValidation: true
  #    internalProjectName: ${{ parameters.internalProjectName }}
  #- template: ../jobs/copy-base-images.yml
  #  parameters:
  #    name: CopyBaseImages
  #    pool: ${{ parameters.linuxAmd64Pool }}
  #    additionalOptions: "--manifest '$(manifest)' $(manifestVariables)"
  #    publicProjectName: ${{ parameters.publicProjectName }}
  - template: ../jobs/generate-matrix.yml
    parameters:
      matrixType: ${{ parameters.buildMatrixType }}
      name: GenerateBuildMatrix
      pool: ${{ parameters.linuxAmd64Pool }}
      customBuildLegGroupArgs: ${{ parameters.buildMatrixCustomBuildLegGroupArgs }}
      internalProjectName: ${{ parameters.internalProjectName }}
      internalVersionsRepoRef: ${{ parameters.internalVersionsRepoRef }}
      publicVersionsRepoRef: ${{ parameters.publicVersionsRepoRef }}
  - template: ../jobs/build-images.yml
    parameters:
      name: Linux_amd64
      pool: ${{ parameters.linuxAmd64Pool }}
      matrix: dependencies.GenerateBuildMatrix.outputs['matrix.LinuxAmd64']
      dockerClientOS: linux
      buildJobTimeout: ${{ parameters.linuxAmdBuildJobTimeout }}
      customInitSteps: ${{ parameters.customBuildInitSteps }}
      noCache: ${{ parameters.noCache }}
      internalProjectName: ${{ parameters.internalProjectName }}
      publicProjectName: ${{ parameters.publicProjectName }}
      internalVersionsRepoRef: ${{ parameters.internalVersionsRepoRef }}
      publicVersionsRepoRef: ${{ parameters.publicVersionsRepoRef }}
