parameters:
  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)

stages:

################################################################################
# Build Images
################################################################################
- stage: Build
  condition: succeeded()
  jobs:
  - template: ../jobs/test-images-linux-client.yml
    parameters:
      name: PreBuildValidation
      pool: ${{ parameters.linuxAmd64Pool }}

