# A wrapper template around the common build-test-publish-repo template with settings
# specific to the .NET team's infrastructure.

parameters:
  noCache: false
  publicProjectName: null
  linuxAmd64Pool:
    vmImage: ubuntu-latest

stages:
- template: ../build-test-publish-repo.yml
  parameters:
    noCache: ${{ parameters.noCache }}
    publicProjectName: pulic

    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
