# A wrapper template around the common build-test-publish-repo template with settings
# specific to the .NET team's infrastructure.

parameters:
  linuxAmd64Pool:
    vmImage: $(defaultLinuxAmd64PoolImage)

stages:
- template: ../build-test-publish-repo.yml
  parameters:
    linuxAmd64Pool: ${{ parameters.linuxAmd64Pool }}
